### ISSUE TITLE
Allow to configure hooks with filenames as well as embedding scripts

### ISSUE THREAD

**Issue by plaffitt** [paullaffitte/shctx#16]
```yaml
my-context:
  enter:
    file: ./enter.sh
  exit: echo "bye bye!"
```
