### ISSUE TITLE
Read contexts configurations

### ISSUE THREAD

**Issue by plaffitt** [paullaffitte/shctx#4]
Example of configuration:

```yaml
ctx_name:
  history_name: optional (defaults to context name, `null` to disable custom history)
  on_enter: |
    echo "entered context"
  on_exit: |
    echo "exited context"
```
